# Project plan

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

Development will take place publicly on the GitHub account: [atsyplenkov/wbw](https://github.com/atsyplenkov/wbw), owned by Anatolii Tsyplenkov. The project package will be licensed compatibly with R and `terra`/`sf` (MIT or GPL >= 2). The project leader will provide the R Consortium with monthly updates based on progress toward the deliverables below.


## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

Each package release will be announced on social media platforms using the `#rstats` tag and on a blog cross-posted to R-bloggers. Due to our location in New Zealand, attending international meetings and conferences is very costly and not eco-friendly. We will submit an abstract to the [FOSS4G Conference](https://2025.foss4g.org/), which will take place in Auckland, New Zealand in November 2025.